- name: Configuring apache2
  hosts: all
  become: yes
  tasks:
   - name: Installing apache2
     apt:
      name: apache2
      state: present
   - name: Edit index.html file
     copy:
      content: /home/ubuntu/index.html
      dest: /var/www/html/index.html
   - name: Restart apache2
     service:
      name: apache2
      state: restarted
   - name: Checking url response
     uri:
      url: http://13.127.117.79
      status: 200
   - name: Checking url response
     uri:
      url: http://13.232.79.32
      status: 200

