---
- name: install packages implement ci-cd
  hosts: all
  become: yes
  tasks:
   - name: install git
     apt:
         name: git
         state: present
   - name: install maven
     apt:
          name: maven
          state: latest
   - name: install java
     apt:
          name: default-jdk
          state: latest
   - name: install tomcat
     apt:
          name: tomcat8
          state: present
          update_cache: yes
   - name: install admin
     apt:
          name: tomcat8-admin
          state: present
          update_cache: yes

- name: Continous Download and Continuous Build
  hosts: DevServer
  tasks:
   - name: Download development code from git
     git:
      repo: https://github.com/selenium-saikrishna/maven.git
      dest: /home/ubuntu/mygit
   - name: Using maven create an artifact
     shell: cd /home/ubuntu/mygit;mvn package
- name: Continuous Deployment and Continuous Tesitng
  hosts: DevServer
  tasks:
   - name: Fetch the artifact from devserver
     fetch:
      src: /home/ubuntu/mygit/webapp/target/webapp.war
      dest: /home/ubuntu
- name: Copy the artifact into qaserver tomcat
  hosts: QAServer
  tasks:
   - name: Copy the artifact
     copy:
      src: /home/ubuntu/13.233.83.38/home/ubuntu/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat8/webapps/qaenv.war
   - name: Download testing code from git
     git:
      repo: https://github.com/selenium-saikrishna/TestingOnAWS.git
      dest: /home/ubuntu/testing
      #   - name: execute the testing programs
      # shell: java -jar /home/ubuntu/testing/testing.jar
- name: Deploy to prod server
  hosts: ProdServer
  tasks:
   - name: Copy the artifact into prodserver
     copy:
      src: /home/ubuntu/13.233.83.38/home/ubuntu/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat8/webapps/prodenv.war
